POST http://localhost:3001/api/polls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1peHUiLCJpZCI6IjY1MWM2ODhjM2EyOWEwNDZhNGNhMDMxNCIsImlhdCI6MTY5NzQ3NzYxMiwiZXhwIjoxNjk3NDgxMjEyfQ.fCmfoyfmSSPnCjudEXcybBDLRMVxITcLXLIguH7OIVU

{
    "title": "favorite color",
    "options":
    [
        {
            "id": 1,
            "option": "black",
            "likes": 0
        },        
        {
            "id": 2,
            "option": "blue",
            "likes": 0
        },
        {
            "id": 3,
            "option": "red",
            "likes": 0
        }
    ]
}