POST http://localhost:3001/api/polls
Content-Type: application/json
Authorization: Bearer token

{
    "title": "how are you",
    "options":
    [
        {
            "id": 1,
            "answer": "good",
            "likes": 0
        },        
        {
            "id": 2,
            "answer": "fine",
            "likes": 0
        },
        {
            "id": 3,
            "answer": "not good",
            "likes": 0
        }
    ]
}